baseURL: 'https://idaikt.sporkify.net/'
languageCode: 'en-us'
title: 'I drink and I know things'
theme: 'hugo-bootstrap-bare'
menu:
  main:
    - identifier: search
      name: "Search"
      url: "/search/"
      weight: 1